# Generated by Django 5.0 on 2024-02-04 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_login", "0003_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="invcode",
            new_name="ivcode",
        ),
    ]
