# Generated by Django 5.0 on 2024-02-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_login", "0004_rename_invcode_event_ivcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="start",
            field=models.BooleanField(default=False),
        ),
    ]
