# Generated by Django 5.0 on 2024-02-10 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_login", "0005_event_ended_event_start"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=300)),
                ("vote", models.IntegerField(default=0)),
                (
                    "eid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_login.event",
                    ),
                ),
            ],
        ),
    ]
